stop_area_dict:
  IXU: "Dibrugarh Airport"
  IDR: "Indore Airport"
  Patna: "Lok Nayak Jayaprakash Airport"
  Indore: "Indore Airport"
  PAT: "Patna Airport"
  MYQ: "Mysore Airport"
  Bhubaneswar: "Biju Patnaik International Airport"
  KLH: "Kochi Airport"
  JGB: "Jagdalpur Airport"
  JRG: "Jorhat Airport"
  STV: "Surat Airport"
  BBI: "Bhubaneswar Airport"
  Delhi: "Indira Gandhi International Airport"
  Hyderabad: "Rajiv Gandhi International Airport"
  IXE: "Mangalore International Airport"
  Ranchi: "Birsa Munda Airport"
  Raipur: "Swami Vivekananda International Airport"
  Chennai: "Chennai International Airport"
  Guwahati: "Lokpriya Gopinath Bordoloi International Airport"
  Mysore: "Mysore Airport"
  Mangalore: "Mangalore International Airport"
  Mumbai: "Chhatrapati Shivaji Maharaj International Airport"
  Kolkata: "Netaji Subhas Chandra Bose International Airport"
  VTZ: "Visakhapatnam Airport"
  Nagpur: "Dr. Babasaheb Ambedkar International Airport"
  NDC: "Dibrugarh Airport"
  RPR: "Raipur Airport"
  GOP: "Gorakhpur Airport"
  Surat: "Surat Airport"
  Lucknow: "Chaudhary Charan Singh International Airport"
  NAG: "Nagpur Airport"
  Vishakhapatnam: "Visakhapatnam International Airport"
  Kolhapur: "Kolhapur Airport"
  IXR: "Ranchi Airport"
  GAY: "Gaya International Airport"
  GAU: "Lokpriya Gopinath Bordoloi International Airport"
  HYD: "Hyderabad International Airport"
