COLUMN_RENAME_MAPPING:
  date: "flight_date"
  airline: "airline_name"
  ch_code: "airline_code"
  num_code: "flight_code"
  dep_time: "departure_time"
  from: "departure_city"
  time_taken: "flight_duration"
  stop: "stop_type"
  arr_time: "arrival_time"
  to: "arrival_city"
  price: "ticket_price"
